In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 100, size=(50,5))
scores_df = pd.DataFrame(scores,
                         columns=['國文','英文','數學','地理','歷史'],
                         index=range(1,51))
scores_df
sum_value = scores_df.sum(axis=1)
mean_value = scores_df.mean(axis=1)
scores_df['總分'] = sum_value
scores_df['平均'] = mean_value

In [2]:
scores_df

    國文  英文  數學  地理  歷史   總分    平均
1   51  78  50  85  89  353  70.6
2   57  69  56  91  70  343  68.6
3   78  87  91  97  74  427  85.4
4   97  81  66  88  59  391  78.2
5   94  61  53  61  58  327  65.4
6   65  96  59  86  82  388  77.6
7   94  95  60  72  70  391  78.2
8   52  51  63  74  72  312  62.4
9   93  61  61  98  97  410  82.0
10  75  73  76  70  77  371  74.2
11  55  82  70  86  63  356  71.2
12  90  51  59  94  77  371  74.2
13  98  87  79  79  84  427  85.4
14  95  74  94  60  52  375  75.0
15  64  67  93  96  86  406  81.2
16  86  84  91  52  97  410  82.0
17  97  74  61  77  84  393  78.6
18  72  70  72  77  88  379  75.8
19  66  93  54  92  52  357  71.4
20  72  73  76  86  99  406  81.2
21  50  80  83  94  89  396  79.2
22  81  83  73  75  70  382  76.4
23  71  96  93  76  99  435  87.0
24  74  51  71  85  55  336  67.2
25  67  78  79  83  87  394  78.8
26  71  98  60  62  60  351  70.2
27  56  59  82  57  71  325  65.0
28  73  66  78  73  59  349  69.8
29  75  57  88  58  99  377  75.4
30  80  65  96  51  52  344  68.8
31  64  63  85  63  59  334  66.8
32  84  64  57  61  66  332  66.4
33  56  59  89  99  77  380  76.0
34  90  97  75  54  75  391  78.2
35  50  88  65  70  97  370  74.0
36  82  91  74  86  51  384  76.8
37  90  54  56  84  73  357  71.4
38  68  62  94  82  84  390  78.0
39  54  79  95  59  75  362  72.4
40  70  99  82  93  72  416  83.2
41  79  69  56  50  91  345  69.0
42  77  76  89  83  90  415  83.0
43  92  66  55  88  96  397  79.4
44  73  84  76  50  77  360  72.0
45  85  52  60  82  91  370  74.0
46  89  66  66  63  81  365  73.0
47  79  96  98  57  79  409  81.8
48  51  93  83  68  65  360  72.0
49  50  50  55  83  99  337  67.4
50  77  99  93  94  70  433  86.6

In [9]:
#排序總分 sort
scores_df.sort_values(by='總分') 
#axis預設值為0，按照欄位排序(上下垂直)，可以不用寫。
#ascending預設值為True，總分由小至大。

    國文  英文  數學  地理  歷史   總分    平均
8   52  51  63  74  72  312  62.4
27  56  59  82  57  71  325  65.0
5   94  61  53  61  58  327  65.4
32  84  64  57  61  66  332  66.4
31  64  63  85  63  59  334  66.8
24  74  51  71  85  55  336  67.2
49  50  50  55  83  99  337  67.4
2   57  69  56  91  70  343  68.6
30  80  65  96  51  52  344  68.8
41  79  69  56  50  91  345  69.0
28  73  66  78  73  59  349  69.8
26  71  98  60  62  60  351  70.2
1   51  78  50  85  89  353  70.6
11  55  82  70  86  63  356  71.2
19  66  93  54  92  52  357  71.4
37  90  54  56  84  73  357  71.4
44  73  84  76  50  77  360  72.0
48  51  93  83  68  65  360  72.0
39  54  79  95  59  75  362  72.4
46  89  66  66  63  81  365  73.0
35  50  88  65  70  97  370  74.0
45  85  52  60  82  91  370  74.0
10  75  73  76  70  77  371  74.2
12  90  51  59  94  77  371  74.2
14  95  74  94  60  52  375  75.0
29  75  57  88  58  99  377  75.4
18  72  70  72  77  88  379  75.8
33  56  59  89  99  77  380  76.0
22  81  83  73  75  70  382  76.4
36  82  91  74  86  51  384  76.8
6   65  96  59  86  82  388  77.6
38  68  62  94  82  84  390  78.0
7   94  95  60  72  70  391  78.2
4   97  81  66  88  59  391  78.2
34  90  97  75  54  75  391  78.2
17  97  74  61  77  84  393  78.6
25  67  78  79  83  87  394  78.8
21  50  80  83  94  89  396  79.2
43  92  66  55  88  96  397  79.4
20  72  73  76  86  99  406  81.2
15  64  67  93  96  86  406  81.2
47  79  96  98  57  79  409  81.8
16  86  84  91  52  97  410  82.0
9   93  61  61  98  97  410  82.0
42  77  76  89  83  90  415  83.0
40  70  99  82  93  72  416  83.2
13  98  87  79  79  84  427  85.4
3   78  87  91  97  74  427  85.4
50  77  99  93  94  70  433  86.6
23  71  96  93  76  99  435  87.0

In [10]:
#總分由大排至小。
#找出分數最低的五名
scores_df.sort_values(by='總分', ascending=False).iloc[-5:]

    國文  英文  數學  地理  歷史   總分    平均
31  64  63  85  63  59  334  66.8
32  84  64  57  61  66  332  66.4
5   94  61  53  61  58  327  65.4
27  56  59  82  57  71  325  65.0
8   52  51  63  74  72  312  62.4

In [11]:
scores_df['平均'] < 70 #比較運算子，傳出布林值。False: >=70；True" <70。

1     False
2      True
3     False
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25    False
26    False
27     True
28     True
29    False
30     True
31     True
32     True
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41     True
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49     True
50    False
Name: 平均, dtype: bool

In [12]:
#使用subscript[]，過濾資料
scores_df[scores_df['平均'] < 80]

    國文  英文  數學  地理  歷史   總分    平均
1   51  78  50  85  89  353  70.6
2   57  69  56  91  70  343  68.6
4   97  81  66  88  59  391  78.2
5   94  61  53  61  58  327  65.4
6   65  96  59  86  82  388  77.6
7   94  95  60  72  70  391  78.2
8   52  51  63  74  72  312  62.4
10  75  73  76  70  77  371  74.2
11  55  82  70  86  63  356  71.2
12  90  51  59  94  77  371  74.2
14  95  74  94  60  52  375  75.0
17  97  74  61  77  84  393  78.6
18  72  70  72  77  88  379  75.8
19  66  93  54  92  52  357  71.4
21  50  80  83  94  89  396  79.2
22  81  83  73  75  70  382  76.4
24  74  51  71  85  55  336  67.2
25  67  78  79  83  87  394  78.8
26  71  98  60  62  60  351  70.2
27  56  59  82  57  71  325  65.0
28  73  66  78  73  59  349  69.8
29  75  57  88  58  99  377  75.4
30  80  65  96  51  52  344  68.8
31  64  63  85  63  59  334  66.8
32  84  64  57  61  66  332  66.4
33  56  59  89  99  77  380  76.0
34  90  97  75  54  75  391  78.2
35  50  88  65  70  97  370  74.0
36  82  91  74  86  51  384  76.8
37  90  54  56  84  73  357  71.4
38  68  62  94  82  84  390  78.0
39  54  79  95  59  75  362  72.4
41  79  69  56  50  91  345  69.0
43  92  66  55  88  96  397  79.4
44  73  84  76  50  77  360  72.0
45  85  52  60  82  91  370  74.0
46  89  66  66  63  81  365  73.0
48  51  93  83  68  65  360  72.0
49  50  50  55  83  99  337  67.4

In [13]:
#有幾位同學平均分數小於80
scores_df[scores_df['平均'] < 80].count()

國文    39
英文    39
數學    39
地理    39
歷史    39
總分    39
平均    39
dtype: int64

In [15]:
#使用subscribe[]的搜尋方式
#平均分數小於80，同時歷史不及格
scores_df[(scores_df['平均'] < 80) & (scores_df['歷史'] < 60)]

    國文  英文  數學  地理  歷史   總分    平均
4   97  81  66  88  59  391  78.2
5   94  61  53  61  58  327  65.4
14  95  74  94  60  52  375  75.0
19  66  93  54  92  52  357  71.4
24  74  51  71  85  55  336  67.2
28  73  66  78  73  59  349  69.8
30  80  65  96  51  52  344  68.8
31  64  63  85  63  59  334  66.8
36  82  91  74  86  51  384  76.8

In [16]:
#使用query()的方式搜尋
scores_df.query('平均<80')

    國文  英文  數學  地理  歷史   總分    平均
1   51  78  50  85  89  353  70.6
2   57  69  56  91  70  343  68.6
4   97  81  66  88  59  391  78.2
5   94  61  53  61  58  327  65.4
6   65  96  59  86  82  388  77.6
7   94  95  60  72  70  391  78.2
8   52  51  63  74  72  312  62.4
10  75  73  76  70  77  371  74.2
11  55  82  70  86  63  356  71.2
12  90  51  59  94  77  371  74.2
14  95  74  94  60  52  375  75.0
17  97  74  61  77  84  393  78.6
18  72  70  72  77  88  379  75.8
19  66  93  54  92  52  357  71.4
21  50  80  83  94  89  396  79.2
22  81  83  73  75  70  382  76.4
24  74  51  71  85  55  336  67.2
25  67  78  79  83  87  394  78.8
26  71  98  60  62  60  351  70.2
27  56  59  82  57  71  325  65.0
28  73  66  78  73  59  349  69.8
29  75  57  88  58  99  377  75.4
30  80  65  96  51  52  344  68.8
31  64  63  85  63  59  334  66.8
32  84  64  57  61  66  332  66.4
33  56  59  89  99  77  380  76.0
34  90  97  75  54  75  391  78.2
35  50  88  65  70  97  370  74.0
36  82  91  74  86  51  384  76.8
37  90  54  56  84  73  357  71.4
38  68  62  94  82  84  390  78.0
39  54  79  95  59  75  362  72.4
41  79  69  56  50  91  345  69.0
43  92  66  55  88  96  397  79.4
44  73  84  76  50  77  360  72.0
45  85  52  60  82  91  370  74.0
46  89  66  66  63  81  365  73.0
48  51  93  83  68  65  360  72.0
49  50  50  55  83  99  337  67.4

In [17]:
scores_df.query('平均<80' and '歷史<60')

    國文  英文  數學  地理  歷史   總分    平均
4   97  81  66  88  59  391  78.2
5   94  61  53  61  58  327  65.4
14  95  74  94  60  52  375  75.0
19  66  93  54  92  52  357  71.4
24  74  51  71  85  55  336  67.2
28  73  66  78  73  59  349  69.8
30  80  65  96  51  52  344  68.8
31  64  63  85  63  59  334  66.8
36  82  91  74  86  51  384  76.8