In [4]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 100, size=(50,5))
scores_df = pd.DataFrame(scores,
                         columns=['國文','英文','數學','地理','歷史'],
                         index=range(1,51))
scores_df
sum_value = scores_df.sum(axis=1)
mean_value = scores_df.mean(axis=1)
scores_df['總分'] = sum_value
scores_df['平均'] = mean_value

In [5]:
scores_df

    國文  英文  數學  地理  歷史   總分    平均
1   69  84  65  80  90  388  77.6
2   64  71  96  64  60  355  71.0
3   91  58  70  75  84  378  75.6
4   61  58  93  50  93  355  71.0
5   63  66  92  50  94  365  73.0
6   92  91  73  59  79  394  78.8
7   84  94  92  67  50  387  77.4
8   97  95  80  88  83  443  88.6
9   64  59  62  56  77  318  63.6
10  53  79  65  93  54  344  68.8
11  95  87  50  79  62  373  74.6
12  87  51  67  80  92  377  75.4
13  56  95  96  52  97  396  79.2
14  57  56  96  83  95  387  77.4
15  91  88  70  64  74  387  77.4
16  93  61  62  57  50  323  64.6
17  59  73  77  90  56  355  71.0
18  59  67  63  81  62  332  66.4
19  51  83  93  84  93  404  80.8
20  68  65  84  68  94  379  75.8
21  57  75  86  78  74  370  74.0
22  91  76  58  74  69  368  73.6
23  74  98  51  62  95  380  76.0
24  60  72  62  63  89  346  69.2
25  53  55  65  80  89  342  68.4
26  53  96  76  91  50  366  73.2
27  80  58  59  82  55  334  66.8
28  74  79  65  64  95  377  75.4
29  55  73  94  88  86  396  79.2
30  78  82  77  61  66  364  72.8
31  93  57  52  68  54  324  64.8
32  59  74  55  69  69  326  65.2
33  71  95  60  78  91  395  79.0
34  63  70  50  83  83  349  69.8
35  54  82  73  81  55  345  69.0
36  83  78  99  95  98  453  90.6
37  67  53  75  56  93  344  68.8
38  69  63  76  58  58  324  64.8
39  89  94  74  66  65  388  77.6
40  83  75  94  73  69  394  78.8
41  95  51  94  99  54  393  78.6
42  87  76  73  81  96  413  82.6
43  77  79  67  79  96  398  79.6
44  70  53  95  52  73  343  68.6
45  88  84  82  87  55  396  79.2
46  90  73  90  73  66  392  78.4
47  57  71  98  56  96  378  75.6
48  99  97  63  98  85  442  88.4
49  50  94  64  57  95  360  72.0
50  76  64  93  64  77  374  74.8

In [6]:
scores_df
scores_df.style.highlight_between(left=50,right=60)

In [7]:
scores_df
scores_df.style\
    .format(precision=2)\
    .highlight_between(left=50,right=59)\
    .to_excel('abc.xlsx')

#\:表示這一行跟下一行接在一起
#.:用句點代表逗號

In [8]:
scores_df
scores_df.style\
    .format(precision=2)\
    .highlight_between(left=50,right=59, props='color:white; background-color:#DB4D6D;')\
    .highlight_max(axis=1, subset=scores_df.columns[:5], props='color:white; background-color:#86C166;')

#可以選擇日本色票作為配色