In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(40, high=101, size=(50, 5))
scores_df = pd.DataFrame(scores, 
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores_df.index.name = "學號"
scores_df.columns.name = "科目"
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
rank_series = sum_series.rank(method='min',ascending=False)
scores_df["總分"] = sum_series
scores_df["平均"] = mean_series
scores_df["名次"] = rank_series
scores_df.sort_values(by="名次")

科目  國文  英文  數學   地理   歷史   總分    平均    名次
學號
31  96  98  79   88  100  461  92.2   1.0
21  80  82  72   90   88  412  82.4   2.0
9   92  51  79   85   96  403  80.6   3.0
3   70  93  61   74   99  397  79.4   4.0
18  59  90  98   93   56  396  79.2   5.0
42  97  57  91   56   92  393  78.6   6.0
24  89  78  61   68   94  390  78.0   7.0
33  76  91  61   93   66  387  77.4   8.0
34  43  90  88   80   86  387  77.4   8.0
39  46  82  96   97   63  384  76.8  10.0
4   77  93  51   84   74  379  75.8  11.0
23  90  66  42   93   87  378  75.6  12.0
35  85  70  72  100   51  378  75.6  12.0
36  59  70  70  100   76  375  75.0  14.0
43  67  84  87   63   73  374  74.8  15.0
17  97  58  80   88   50  373  74.6  16.0
10  76  99  73   48   76  372  74.4  17.0
29  42  97  87   66   79  371  74.2  18.0
25  45  74  75   88   86  368  73.6  19.0
49  60  96  81   83   46  366  73.2  20.0
8   41  65  75   91   93  365  73.0  21.0
20  73  67  92   77   52  361  72.2  22.0
12  89  56  86   63   67  361  72.2  22.0
47  44  92  51   98   76  361  72.2  22.0
14  97  86  43   82   52  360  72.0  25.0
22  77  48  86   58   85  354  70.8  26.0
44  45  75  97   68   68  353  70.6  27.0
30  69  56  72   66   88  351  70.2  28.0
1   70  71  80   89   41  351  70.2  28.0
16  82  70  42   72   85  351  70.2  28.0
13  78  44  88   94   45  349  69.8  31.0
7   46  98  75   78   52  349  69.8  31.0
5   93  67  63   46   71  340  68.0  33.0
15  81  43  76   85   49  334  66.8  34.0
38  56  72  52   64   88  332  66.4  35.0
32  52  77  90   62   47  328  65.6  36.0
2   49  66  63   53   94  325  65.0  37.0
41  43  96  53   69   56  317  63.4  38.0
37  41  51  82   53   87  314  62.8  39.0
26  56  73  54   41   88  312  62.4  40.0
28  73  63  47   86   42  311  62.2  41.0
46  42  73  44   77   74  310  62.0  42.0
27  46  83  53   51   76  309  61.8  43.0
48  49  51  69   67   66  302  60.4  44.0
11  61  50  60   74   56  301  60.2  45.0
6   40  77  67   61   51  296  59.2  46.0
50  62  44  43   45   94  288  57.6  47.0
45  40  81  46   61   57  285  57.0  48.0
40  47  46  59   73   59  284  56.8  49.0
19  49  59  40   71   47  266  53.2  50.0

In [2]:
scores_df.iloc[:3]

科目  國文  英文  數學  地理  歷史   總分    平均    名次
學號
1   70  71  80  89  41  351  70.2  28.0
2   49  66  63  53  94  325  65.0  37.0
3   70  93  61  74  99  397  79.4   4.0

In [5]:
scores_df.iloc[-3:]

科目  國文  英文  數學  地理  歷史   總分    平均    名次
學號
48  49  51  69  67  66  302  60.4  44.0
49  60  96  81  83  46  366  73.2  20.0
50  62  44  43  45  94  288  57.6  47.0

In [6]:
display(scores_df.iloc[:3])
new_df = scores_df.iloc[:3].copy()
new_df["不及格"] = pd.Series([1,0,2], index=[1,2,3])
new_df

科目  國文  英文  數學  地理  歷史   總分    平均    名次
學號
1   70  71  80  89  41  351  70.2  28.0
2   49  66  63  53  94  325  65.0  37.0
3   70  93  61  74  99  397  79.4   4.0

科目  國文  英文  數學  地理  歷史   總分    平均    名次  不及格
學號
1   70  71  80  89  41  351  70.2  28.0    1
2   49  66  63  53  94  325  65.0  37.0    0
3   70  93  61  74  99  397  79.4   4.0    2

In [12]:
def fun3(series:pd.Series) -> int:
    return series[series<=60].count()

less60Count = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(fun3,axis=1)
less60Count

學號
1     1
2     2
3     0
4     1
5     1
6     2
7     2
8     1
9     1
10    1
11    3
12    1
13    2
14    2
15    2
16    1
17    2
18    2
19    4
20    1
21    0
22    2
23    1
24    0
25    1
26    3
27    3
28    2
29    1
30    1
31    0
32    2
33    0
34    1
35    1
36    1
37    3
38    2
39    1
40    4
41    3
42    2
43    0
44    1
45    3
46    2
47    2
48    2
49    2
50    3
dtype: int64

In [13]:
scores_df["不及格"] = less60Count
scores_df

科目  國文  英文  數學   地理   歷史   總分    平均    名次  不及格
學號
1   70  71  80   89   41  351  70.2  28.0    1
2   49  66  63   53   94  325  65.0  37.0    2
3   70  93  61   74   99  397  79.4   4.0    0
4   77  93  51   84   74  379  75.8  11.0    1
5   93  67  63   46   71  340  68.0  33.0    1
6   40  77  67   61   51  296  59.2  46.0    2
7   46  98  75   78   52  349  69.8  31.0    2
8   41  65  75   91   93  365  73.0  21.0    1
9   92  51  79   85   96  403  80.6   3.0    1
10  76  99  73   48   76  372  74.4  17.0    1
11  61  50  60   74   56  301  60.2  45.0    3
12  89  56  86   63   67  361  72.2  22.0    1
13  78  44  88   94   45  349  69.8  31.0    2
14  97  86  43   82   52  360  72.0  25.0    2
15  81  43  76   85   49  334  66.8  34.0    2
16  82  70  42   72   85  351  70.2  28.0    1
17  97  58  80   88   50  373  74.6  16.0    2
18  59  90  98   93   56  396  79.2   5.0    2
19  49  59  40   71   47  266  53.2  50.0    4
20  73  67  92   77   52  361  72.2  22.0    1
21  80  82  72   90   88  412  82.4   2.0    0
22  77  48  86   58   85  354  70.8  26.0    2
23  90  66  42   93   87  378  75.6  12.0    1
24  89  78  61   68   94  390  78.0   7.0    0
25  45  74  75   88   86  368  73.6  19.0    1
26  56  73  54   41   88  312  62.4  40.0    3
27  46  83  53   51   76  309  61.8  43.0    3
28  73  63  47   86   42  311  62.2  41.0    2
29  42  97  87   66   79  371  74.2  18.0    1
30  69  56  72   66   88  351  70.2  28.0    1
31  96  98  79   88  100  461  92.2   1.0    0
32  52  77  90   62   47  328  65.6  36.0    2
33  76  91  61   93   66  387  77.4   8.0    0
34  43  90  88   80   86  387  77.4   8.0    1
35  85  70  72  100   51  378  75.6  12.0    1
36  59  70  70  100   76  375  75.0  14.0    1
37  41  51  82   53   87  314  62.8  39.0    3
38  56  72  52   64   88  332  66.4  35.0    2
39  46  82  96   97   63  384  76.8  10.0    1
40  47  46  59   73   59  284  56.8  49.0    4
41  43  96  53   69   56  317  63.4  38.0    3
42  97  57  91   56   92  393  78.6   6.0    2
43  67  84  87   63   73  374  74.8  15.0    0
44  45  75  97   68   68  353  70.6  27.0    1
45  40  81  46   61   57  285  57.0  48.0    3
46  42  73  44   77   74  310  62.0  42.0    2
47  44  92  51   98   76  361  72.2  22.0    2
48  49  51  69   67   66  302  60.4  44.0    2
49  60  96  81   83   46  366  73.2  20.0    2
50  62  44  43   45   94  288  57.6  47.0    3

In [16]:
scores_df["平均"]

學號
1     70.2
2     65.0
3     79.4
4     75.8
5     68.0
6     59.2
7     69.8
8     73.0
9     80.6
10    74.4
11    60.2
12    72.2
13    69.8
14    72.0
15    66.8
16    70.2
17    74.6
18    79.2
19    53.2
20    72.2
21    82.4
22    70.8
23    75.6
24    78.0
25    73.6
26    62.4
27    61.8
28    62.2
29    74.2
30    70.2
31    92.2
32    65.6
33    77.4
34    77.4
35    75.6
36    75.0
37    62.8
38    66.4
39    76.8
40    56.8
41    63.4
42    78.6
43    74.8
44    70.6
45    57.0
46    62.0
47    72.2
48    60.4
49    73.2
50    57.6
Name: 平均, dtype: float64

In [19]:
#平均分數低於70分
def fun4(value:float) -> str:
    return "禁假" if value <70 else "不禁假"

scores_df["禁假"] = scores_df["平均"].map(fun4)
scores_df

科目  國文  英文  數學   地理   歷史   總分    平均    名次  不及格   禁假
學號
1   70  71  80   89   41  351  70.2  28.0    1  不禁假
2   49  66  63   53   94  325  65.0  37.0    2   禁假
3   70  93  61   74   99  397  79.4   4.0    0  不禁假
4   77  93  51   84   74  379  75.8  11.0    1  不禁假
5   93  67  63   46   71  340  68.0  33.0    1   禁假
6   40  77  67   61   51  296  59.2  46.0    2   禁假
7   46  98  75   78   52  349  69.8  31.0    2   禁假
8   41  65  75   91   93  365  73.0  21.0    1  不禁假
9   92  51  79   85   96  403  80.6   3.0    1  不禁假
10  76  99  73   48   76  372  74.4  17.0    1  不禁假
11  61  50  60   74   56  301  60.2  45.0    3   禁假
12  89  56  86   63   67  361  72.2  22.0    1  不禁假
13  78  44  88   94   45  349  69.8  31.0    2   禁假
14  97  86  43   82   52  360  72.0  25.0    2  不禁假
15  81  43  76   85   49  334  66.8  34.0    2   禁假
16  82  70  42   72   85  351  70.2  28.0    1  不禁假
17  97  58  80   88   50  373  74.6  16.0    2  不禁假
18  59  90  98   93   56  396  79.2   5.0    2  不禁假
19  49  59  40   71   47  266  53.2  50.0    4   禁假
20  73  67  92   77   52  361  72.2  22.0    1  不禁假
21  80  82  72   90   88  412  82.4   2.0    0  不禁假
22  77  48  86   58   85  354  70.8  26.0    2  不禁假
23  90  66  42   93   87  378  75.6  12.0    1  不禁假
24  89  78  61   68   94  390  78.0   7.0    0  不禁假
25  45  74  75   88   86  368  73.6  19.0    1  不禁假
26  56  73  54   41   88  312  62.4  40.0    3   禁假
27  46  83  53   51   76  309  61.8  43.0    3   禁假
28  73  63  47   86   42  311  62.2  41.0    2   禁假
29  42  97  87   66   79  371  74.2  18.0    1  不禁假
30  69  56  72   66   88  351  70.2  28.0    1  不禁假
31  96  98  79   88  100  461  92.2   1.0    0  不禁假
32  52  77  90   62   47  328  65.6  36.0    2   禁假
33  76  91  61   93   66  387  77.4   8.0    0  不禁假
34  43  90  88   80   86  387  77.4   8.0    1  不禁假
35  85  70  72  100   51  378  75.6  12.0    1  不禁假
36  59  70  70  100   76  375  75.0  14.0    1  不禁假
37  41  51  82   53   87  314  62.8  39.0    3   禁假
38  56  72  52   64   88  332  66.4  35.0    2   禁假
39  46  82  96   97   63  384  76.8  10.0    1  不禁假
40  47  46  59   73   59  284  56.8  49.0    4   禁假
41  43  96  53   69   56  317  63.4  38.0    3   禁假
42  97  57  91   56   92  393  78.6   6.0    2  不禁假
43  67  84  87   63   73  374  74.8  15.0    0  不禁假
44  45  75  97   68   68  353  70.6  27.0    1  不禁假
45  40  81  46   61   57  285  57.0  48.0    3   禁假
46  42  73  44   77   74  310  62.0  42.0    2   禁假
47  44  92  51   98   76  361  72.2  22.0    2  不禁假
48  49  51  69   67   66  302  60.4  44.0    2   禁假
49  60  96  81   83   46  366  73.2  20.0    2  不禁假
50  62  44  43   45   94  288  57.6  47.0    3   禁假